package com.eviware.soapui.analytics;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by aleshin on 5/15/2014.
 */

public class AnalyticsManager {

    private static AnalyticsManager instance = null;
    List<AnalyticsProvider> providers = new ArrayList<AnalyticsProvider>();
    List<AnalyticsProvider.ActionDescription> actions = new ArrayList<AnalyticsProvider.ActionDescription>();

    private String sessionId;
    private List<AnalyticsProviderFactory> factories = new ArrayList<AnalyticsProviderFactory>();

    AnalyticsManager() {

        Date date = new Date();
        String newString = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(date);
        sessionId = String.format("AutoGeneratedSessionId:%s", newString);
    }

    public static AnalyticsManager initialize() {
        if (instance == null) {
            instance = new AnalyticsManager();
        }

        return getAnalytics();
    }

    public static AnalyticsManager getAnalytics() {

        if (instance == null) {
            initialize();
        }

        return instance;
    }

    public void trackAction(String action, Map<String, String> params) {
        trackAction(Category.ACTION, action, params);
    }

    public void trackActiveScreen(String screenName) {

        for (int i = 0; i < providers.size(); i++) {
            providers.get(i).trackActiveScreen(screenName);
        }

    }

    public void trackError(String errorText) {

        for (int i = 0; i < providers.size(); i++) {
            providers.get(i).trackError(errorText);
        }

    }

    public void trackError(Throwable error) {

        for (int i = 0; i < providers.size(); i++) {
            providers.get(i).trackError(error);
        }

    }

    public boolean trackAction(String actionName) {
        return this.trackAction(Category.ACTION, actionName, null);
    }

    // Single param action
    public boolean trackAction(String actionName, String paramName, String value) {

        Map<String, String> params = new HashMap<String, String>();
        params.put(paramName, value);

        return trackAction(Category.ACTION, actionName, params);
    }

    public boolean trackSessionStart() {
        return trackAction(Category.SESSION_START, "", null);
    }

    public boolean trackSessionStop() {
        return trackAction(Category.SESSION_STOP, "", null);
    }

    protected void registerActiveProvider(AnalyticsProvider provider, boolean keepTheOnlyOne) {
        if (keepTheOnlyOne) {
            providers.clear();
        }
        providers.add(provider);
    }

    public void registerAnalyticsProviderFactory(AnalyticsProviderFactory factory) {
        factories.add(factory);
        // if (factories.size() == 1) {
        registerActiveProvider(factory.allocateProvider(), false);
        // }
    }

    public boolean selectAnalyticsProvider(String name, boolean keepTheOnlyOne) {
        for (int i = 0; i < factories.size(); i++) {
            AnalyticsProviderFactory factory = factories.get(i);
            if (factory.getName().compareToIgnoreCase(name) == 0) {
                registerActiveProvider(factory.allocateProvider(), keepTheOnlyOne);
                return true;
            }
        }
        if (keepTheOnlyOne) {
            // A way to stop logging
            providers.clear();
        }
        return false;
    }

    abstract class ActionDescrRunnable implements Runnable {

        AnalyticsProvider.ActionDescription ad;

        ActionDescrRunnable(AnalyticsProvider.ActionDescription ad) {
            this.ad = ad;
        }
    }


    private boolean trackAction(Category category, String action, Map<String, String> params) {

        if (providers.isEmpty()) {
            return false;
        }

        AnalyticsProvider.ActionDescription actionDescr = new AnalyticsProvider.ActionDescription(sessionId, category, action, params);

        new Thread(new ActionDescrRunnable(actionDescr) {
            public void run() {
                for (int i = 0; i < providers.size(); i++) {
                    providers.get(i).trackAction(ad);
                }
            }
        }).start();

        return providers.size() > 0;
    }

    public enum Category {SESSION_START, SESSION_STOP, ACTION}
}
