name: CI/CD

on:
  push:
    branches: [ '**' ]
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install xvfb
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y xvfb

      - name: Set Version and Build Project
        shell: pwsh
        run: |
          $baseVersion = (Select-String -Path 'pom.xml' -Pattern '<revision>(.*)-SNAPSHOT</revision>').Matches.Groups[1].Value
          if ("${{ github.event_name }}" -eq "release") {
            $version = "${{ github.ref_name }}"
          }
          else {
            $timestamp = Get-Date -Format "yyyy-MM-dd"
            $version = "$baseVersion-$timestamp-${{ github.repository_owner }}-${{ github.ref_name }}-SNAPSHOT"
          }
          echo "PROJECT_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          if ("${{ runner.os }}" -eq "Linux") {
            xvfb-run mvn -P assembly,installer "-Dinstall4j.licenseKey=${{ secrets.INSTALL4J_LICENSE_KEY }}" -Drevision=$version clean install
          }
          else {
            mvn -P assembly,installer "-Dinstall4j.licenseKey=${{ secrets.INSTALL4J_LICENSE_KEY }}" -Drevision=$version -DskipTests clean install
          }
      - name: Upload Linux Assets
        if: github.event_name == 'release' && matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            soapui-installer/target/assemblies/*-linux-bin.tar.gz
            soapui-installer/target/install4j/*.sh

      - name: Upload Windows Assets
        if: github.event_name == 'release' && matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            soapui-installer/target/assemblies/*-windows-bin.zip
            soapui-installer/target/install4j/*.exe

      - name: Upload macOS Assets
        if: github.event_name == 'release' && matrix.os == 'macos-13'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            soapui-installer/target/assemblies/*-mac-*.zip
            soapui-installer/target/install4j/*.dmg
